# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: message_broker.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14message_broker.proto\x12\x0emessage_broker\"0\n\x0eMessageRequest\x12\r\n\x05topic\x18\x01 \x01(\t\x12\x0f\n\x07message\x18\x02 \x01(\t\"3\n\x0fMessageResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\"\x1d\n\x0cTopicRequest\x12\r\n\x05topic\x18\x01 \x01(\t\")\n\x07Message\x12\r\n\x05topic\x18\x01 \x01(\t\x12\x0f\n\x07message\x18\x02 \x01(\t2\xba\x01\n\x14MessageBrokerService\x12S\n\x0ePublishMessage\x12\x1e.message_broker.MessageRequest\x1a\x1f.message_broker.MessageResponse\"\x00\x12M\n\x10SubscribeToTopic\x12\x1c.message_broker.TopicRequest\x1a\x17.message_broker.Message\"\x00\x30\x01\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'message_broker_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _MESSAGEREQUEST._serialized_start=40
  _MESSAGEREQUEST._serialized_end=88
  _MESSAGERESPONSE._serialized_start=90
  _MESSAGERESPONSE._serialized_end=141
  _TOPICREQUEST._serialized_start=143
  _TOPICREQUEST._serialized_end=172
  _MESSAGE._serialized_start=174
  _MESSAGE._serialized_end=215
  _MESSAGEBROKERSERVICE._serialized_start=218
  _MESSAGEBROKERSERVICE._serialized_end=404
# @@protoc_insertion_point(module_scope)
